version: "3"

services:
  core:
    container_name: core
    hostname: core
    image: massmux/bitcoincore
    environment:
      - BX_CONFIG=/opt/nodeworkdir/bx.cfg
    volumes:
      - ./bitcoin:/root/.bitcoin
      - ./nodeworkdir:/opt/nodeworkdir
    entrypoint: /root/run.sh
    working_dir: /opt/nodeworkdir
    ports:
      - 18443:18443
      - 18444:18444


  electrumx:
    container_name: electrumx
    hostname: electrumx
    image: lukechilds/electrumx
    volumes:
      - ./electrumx:/data
    environment:
      - DAEMON_URL=http://bitcoin:8473@core:8332
      - COIN=BitcoinSegwit
    links:
      - core
    ports:
      - 50002:50002

  lnd:
    container_name: lnd
    hostname: lnd
    image: lightninglabs/lnd:v0.12.1-beta
    volumes:
      - ./lnd/lnd-data:/root/.lnd
      - ./lnd/entrypoint.sh:/opt/entrypoint.sh
    entrypoint: ["/opt/entrypoint.sh"]
    environment:
      - NETWORK=mainnet
      - CHAIN=bitcoin
      - BACKEND=bitcoind
      - RPCUSER=bitcoin
      - RPCPASS=8473
      - HOSTNAME=0.0.0.0
      - BACKEND_RPC_HOST=core
      - BACKEND_ZMQPUBRAWBLOCK=tcp://core:38444
      - BACKEND_ZMQPUBRAWTX=tcp://core:48444
    ports:
      - 10009:10009
      - 19735:9735
    links:
      - core


